# Generated by Django 6.0.7 on 2026-08-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Customer", "Customer"),
                    ("Seller", "Seller"),
                    ("Admin", "Admin"),
                ],
                default="Customer",
                max_length=20,
            ),
        ),
    ]
